---
  - name: creating webserver on multiple nodes
    hosts: all
    tasks: 
        - name: install httpd
          dnf:
            name: httpd
            state: present

        - name: start and enable httpd
          service:
            name: httpd
            state: started
            enabled: yes

        - name: copy index file from present directory
          copy:
            src: index.html
            dest: /var/www/html

  - name: allow port in firewall for the RHEL9 machines
    hosts: node
    tasks:
      - name: allow the http port in firewalld
        firewalld:
            service: http
            state: present
            permanent: yes
            immediate: yes
